### PR TITLE
Fix reload problem with separate CSS files

### LINKED ISSUE #356: Separate CSS file not reloading on change
I've run into a case, where I had a component in `templates/` folder (`src/templates/user/-components/user-agent.{gts,css}`). I noticed, there are two issues with that.

## 1. Double the File

I saw a strange behavior in which the CSS file showed up twice in `<head>`:

Image

When I made a change, then only the unprocessed file `user-agent.css` was changed, but that was also the wrong file. Here I found the culprit real quick:

```ts
// src/app.ts

export default class App extends EmberApp {
  modules = {
    // ...
    ...import.meta.glob('./templates/**/*', { eager: true })
  };
}
```

that can be fixed with:

```
// src/app.ts

export default class App extends EmberApp {
  modules = {
    // ...
    ...import.meta.glob(['./templates/**/*', '!./templates/**/*.css'], { eager: true })
  };
}
```

that excludes CSS files, that are considered for scoped usage (all for me). That needs documentation.

## 2. Proceesed file does not change Contents

But the file processed by `ember-scoped-css` is not refreshing. I see the import statement is injected into the transpiled component gts file:

Image

And the hashed css file, that got all the vite snippet for hmr in it:

Image

... but that does not HMR 😬 The browser is reloading, but the contents of the file stay the same. Can you nudge me, which code function from `ember-scoped-css` is responisble for that, then I can take a look at fixing that.

### PR DESCRIPTION
**Pull request by gossi**
Fixes #356

Also it improves the readability for `<link>` in head during development for better debugging. It changes the `href`:

- For `<style>`: `/path/to/component-[hash].css`
- For separate CSS File: `/path/to/component.css?scoped=[hash]`

The reason being vite handles CSS files itself with HMR already. When the URL is changed (different resolve), then the original file is no longer watched. The idea is to keep the original URL with a `?scoped=[hash]` then use the `transform()` hook in unplugin to rewrite the CSS.

That also means, the unplugin needs the config, that was previously only needed for the template plugin.

### CODE REVIEW

File: ember-scoped-css/src/build/scoped-css-unplugin.js [hunk 1]
```diff
@@ -1,39 +1,130 @@
...
+      // vite: transform separate CSS file
+      if (isSeparateCSSFileRequest(id)) {
+        const parsed = decodeSeparateCSSFileRequest(id);
+        const filePath = meta?.fileName ?? path.relative(cwd(), id);
+
+        return rewriteCss(code, parsed.postfix, filePath, options.layerName);
+      }
+    },
+
+    // this below is actually the format for transforms, so rust based runtimes
```
Comment (NullVoxPopuli) [inline ember-scoped-css/src/build/scoped-css-unplugin.js]: leftover comment

File: ember-scoped-css/src/build/scoped-css-unplugin.js [hunk 2]
```diff
@@ -1,39 +1,130 @@
...
 /**
- * The plugin that handles CSS requests from other transform (e.g.: babel)
- *
- * This plugin takes no options because the CSS transform has already happened by the time
- * we handle it here.
+ * The plugin that handles CSS requests for `<style>` elements and transforms
+ * for existing files
  */
-export default createUnplugin(() => {
+export default createUnplugin((options = {}) => {
```
[the remark this answers is not in the document]
Comment (NullVoxPopuli) [reply ember-scoped-css/src/build/scoped-css-unplugin.js]: Added to this PR

File: ember-scoped-css/src/build/scoped-css-unplugin.js [hunk 3]
```diff
@@ -1,39 +1,122 @@
...
+          );
+          const relativeFilePath = path.relative(CWD, filePath);
+          
+          let code = readFileSync(filePath, 'utf-8');
+          let css = rewriteCss(
+            code,
+            parsed.postfix,
+            relativeFilePath,
+            options.layerName,
+          );
```
Comment (gossi) [inline ember-scoped-css/src/build/scoped-css-unplugin.js]: you wanna leave that in `transform()` - as this is what's happening. More of a semantic thing, but nevertheless
